version: '3'

services:
  app:
    build: ./python
    container_name: python
    tty: true
    volumes:
      - ../src:/src

  db:
    build: ./mysql
    container_name: mysql
    ports:
      - 3306:3306
    env_file:
      - ../src/.env
