version: "3"

services:
  app:
    build: ./python
    container_name: python
    tty: true
    volumes:
      - ../:/workspace
      - ~/.zshrc-docker:/root/.zshrc
      - ~/.zlogin:/root/.zlogin
      - ~/.zprofile:/root/.zprofile
      - ~/.zenv:/root/.zenv
      - ~/.gitconfig:/root/.gitconfig
      - ~/.commit_template:/root/.commit_template
      - ~/.ssh/id_rsa_github:/root/.ssh/id_rsa_github

  db:
    build: ./mysql
    container_name: mysql
    ports:
      - 3306:3306
    env_file:
      - ../.env
